Fixed some typos on my README.md
AstroHackWeek/2022_contributing_to_open_source pull request #21
Opened 2022-10-19 10:09 UTC by Alonso-Guerrero

Fixed some bad spelling

2022-10-19 10:13 UTC, BSGalvan commented on participants/Guerrero/doc/README.md
> +functions that do stuff and they are:
Great start!
You may want to restructure the narration a little bit more, so that it is more descriptive than what it is currently.

2022-10-19 10:15 UTC, BSGalvan commented on participants/Guerrero/doc/README.md
>      9
This needs to be changed as well.
```suggestion
3628800
```

2022-10-19 10:15 UTC, BSGalvan requested changes
Great start, but needs a little bit more cleanup before it is ready for merging.

2022-10-19 10:31 UTC, PatriziaBussatori commented
Great work

2022-10-20 09:21 UTC, merged

2022-10-20 09:21 UTC, ceb8 commented
Thanks! 😄